### ISSUE TITLE
Region Error

### ISSUE THREAD

**Issue by iamcoreyg** [imgproxy/imgproxy-aws-sam#1]
Hi all,

For context, I'm following this tutorial: https://imgproxy.net/blog/almost-free-image-processing-with-imgproxy-and-aws-lambda/

When I deploy to CloudFormation using the template, I got this error:
AWS::CloudFront::Distribution: The parameter region us-west-1 does not exist!

![image](https://github.com/imgproxy/imgproxy-aws-sam/assets/3101397/4e03d777-4fef-46f5-b115-152fe4d6e821)

Any idea how I can resolve?

**Comment by DarthSim** [comment]
Hey @iamcoreyg!

Turns out, that not all the regions have CloudFront Origin Shield... 🤦‍♂️ I added mapping for CF OS regions, should work now.

**Comment by iamcoreyg** [comment]
@DarthSim thanks for looking into it, it works now!
