### ISSUE TITLE
Activate HTTP2/3 on CF

### ISSUE THREAD

**Issue by Rahe** [imgproxy/imgproxy-aws-sam#3]
Hello,

Thank you very much for the template :)
Is it possible to activate http2/3 automatically on CloudFront ?

Nicolas,

**Comment by sinuheshinbr** [comment]
yes, go to Cloudfront console => Distributions => click on your distribution ID => edit Settings => Select HTTP/2, HTTP/3 and save changes.

**Comment by Rahe** [comment]
Hello,

I've think about activating it from the config file, but manually is great too :)

Nicolas,

**Comment by DarthSim** [comment]
Released a [new version](https://github.com/imgproxy/imgproxy-aws-sam/releases/tag/v0.2.2) that uses HTTP/2/3 for CF by default.
